{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-starter-base.fullname" . }}        
  labels:
    {{- include "helm-starter-base.labels" . | nindent 4 }}
data:
  master: {{ tpl .Values.configmap.master . | quote }}
{{- end }}
