apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-starter-base.fullname" . }}
  labels:
    {{- include "helm-starter-base.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-starter-base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
      labels:
        {{- include "helm-starter-base.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-starter-base.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: volume-{{ include "helm-starter-base.fullname" . }}-config
          configMap:
            name: {{ include "helm-starter-base.fullname" . }}        
            items:
              - key: master
                path: master.yaml
        - name: volume-{{ include "helm-starter-base.fullname" . }}-database
          persistentVolumeClaim:
            claimName: volume-{{include "helm-starter-base.fullname" . }}-database
        - name: volume-{{ include "helm-starter-base.fullname" . }}-git
          persistentVolumeClaim:
            claimName: volume-{{include "helm-starter-base.fullname" . }}-git
        - name: volume-{{ include "helm-starter-base.fullname" . }}-filesystem
          persistentVolumeClaim:
            claimName: volume-{{include "helm-starter-base.fullname" . }}-filesystem
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: volume-{{ include "helm-starter-base.fullname" . }}-config
              mountPath: "/limix/server/master/master.yaml"
              subPath: master.yaml
              readOnly: true
            - name: volume-{{ include "helm-starter-base.fullname" . }}-database
              mountPath: "/limix/data/master/database"
            - name: volume-{{ include "helm-starter-base.fullname" . }}-git
              mountPath: "/limix/data/master/git"
            - name: volume-{{ include "helm-starter-base.fullname" . }}-filesystem
              mountPath: "/limix/data/master/filesystem"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
