{{- if .Values.configmap }}
{{- $master_confs := toYaml .Values.master | nindent 4 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-starter-base.fullname" . }}
  labels:
    {{- include "helm-starter-base.labels" . | nindent 4 }}
data:
  master: {{ tpl $master_confs . -}}
{{- end }}