apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-starter-base.fullname" . }}
  labels:
    {{- include "helm-starter-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.pubsub.port }}
      targetPort: {{ .Values.service.pubsub.targetPort }}
      protocol: {{ .Values.service.pubsub.protocl }}
      hostPort: {{ .Values.service.pubsub.hostPort }}
      name: tcp-pubsub
    - port: {{ .Values.service.return.port }}
      targetPort: {{ .Values.service.return.targetPort }}
      protocol: {{ .Values.service.return.protocol }}
      hostPort: {{ .Values.service.pubsub.hostPort }}
      name: tcp-return
  selector:
    {{- include "helm-starter-base.selectorLabels" . | nindent 4 }}