# This is a basic workflow to help you get started with Actions

name: CI

permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
            ref: 'master'
            path: 'master'
      
      - uses: actions/checkout@v3
        with:
          ref: 'repo'
          path: 'repo' 
      
      - name: Helm Package
        env:
          HELM_VERSION: v3.11.3
        run: |
          wget https://get.helm.sh/helm-v3.11.3-linux-amd64.tar.gz
          tar xvzf helm-v3.11.3-linux-amd64.tar.gz
          linux-amd64/helm package master
          
      - name: Move repo folder
        run: |
          mv *.tar.gz repo/
          cd repo
          git config user.email "coollimix@gmail.com"
          git config user.name "limix"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update repo [SKIP CI]" -m "${{ github.event.head_commit.message }}"
          git push
